/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 04 07:34:16 GMT 2020
 */

package array;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import array.PlusOne;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class PlusOne_ESTest extends PlusOne_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      PlusOne plusOne0 = new PlusOne();
      int[] intArray0 = new int[2];
      int[] intArray1 = plusOne0.plusOne(intArray0);
      assertArrayEquals(new int[] {0, 1}, intArray1);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      PlusOne plusOne0 = new PlusOne();
      int[] intArray0 = new int[1];
      intArray0[0] = 2662;
      int[] intArray1 = plusOne0.plusOne(intArray0);
      assertArrayEquals(new int[] {2663}, intArray1);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      PlusOne plusOne0 = new PlusOne();
      // Undeclared exception!
      try { 
        plusOne0.plusOne((int[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("array.PlusOne", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      PlusOne plusOne0 = new PlusOne();
      int[] intArray0 = new int[4];
      intArray0[3] = 9;
      int[] intArray1 = plusOne0.plusOne(intArray0);
      assertArrayEquals(new int[] {0, 0, 1, 0}, intArray1);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      PlusOne plusOne0 = new PlusOne();
      int[] intArray0 = new int[1];
      intArray0[0] = 9;
      int[] intArray1 = plusOne0.plusOne(intArray0);
      assertArrayEquals(new int[] {1, 0}, intArray1);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      int[] intArray0 = new int[3];
      intArray0[2] = (-134);
      PlusOne plusOne0 = new PlusOne();
      int[] intArray1 = plusOne0.plusOne(intArray0);
      assertArrayEquals(new int[] {0, 0, (-133)}, intArray1);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      PlusOne plusOne0 = new PlusOne();
      int[] intArray0 = new int[0];
      int[] intArray1 = plusOne0.plusOne(intArray0);
      assertSame(intArray1, intArray0);
  }
}
