/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 04 07:34:44 GMT 2020
 */

package array;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import array.RemoveDuplicates;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class RemoveDuplicates_ESTest extends RemoveDuplicates_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      RemoveDuplicates removeDuplicates0 = new RemoveDuplicates();
      assertNotNull(removeDuplicates0);
      
      int[] intArray0 = new int[2];
      intArray0[0] = 1882;
      int int0 = removeDuplicates0.removeDuplicates(intArray0);
      assertEquals(2, intArray0.length);
      assertArrayEquals(new int[] {1882, 0}, intArray0);
      assertEquals(2, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      RemoveDuplicates removeDuplicates0 = new RemoveDuplicates();
      assertNotNull(removeDuplicates0);
      
      int[] intArray0 = new int[0];
      int int0 = removeDuplicates0.removeDuplicates(intArray0);
      assertEquals(0, intArray0.length);
      assertArrayEquals(new int[] {}, intArray0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      int[] intArray0 = new int[7];
      RemoveDuplicates removeDuplicates0 = new RemoveDuplicates();
      assertNotNull(removeDuplicates0);
      
      int int0 = removeDuplicates0.removeDuplicates(intArray0);
      assertEquals(7, intArray0.length);
      assertArrayEquals(new int[] {0, Integer.MAX_VALUE, Integer.MAX_VALUE, Integer.MAX_VALUE, Integer.MAX_VALUE, Integer.MAX_VALUE, Integer.MAX_VALUE}, intArray0);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      int[] intArray0 = new int[2];
      intArray0[0] = (-2817);
      RemoveDuplicates removeDuplicates0 = new RemoveDuplicates();
      int int0 = removeDuplicates0.removeDuplicates(intArray0);
      assertEquals(2, int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      RemoveDuplicates removeDuplicates0 = new RemoveDuplicates();
      // Undeclared exception!
      try { 
        removeDuplicates0.removeDuplicates((int[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("array.RemoveDuplicates", e);
      }
  }
}
