/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 04 07:39:19 GMT 2020
 */

package array;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import array.RotateMatrix;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class RotateMatrix_ESTest extends RotateMatrix_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      RotateMatrix rotateMatrix0 = new RotateMatrix();
      int[][] intArray0 = new int[8][0];
      int[] intArray1 = new int[3];
      intArray0[7] = intArray1;
      // Undeclared exception!
      try { 
        rotateMatrix0.rotate(intArray0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 7, Size: 3
         //
         verifyException("java.util.ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      RotateMatrix rotateMatrix0 = new RotateMatrix();
      // Undeclared exception!
      try { 
        rotateMatrix0.rotate((int[][]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("array.RotateMatrix", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      RotateMatrix rotateMatrix0 = new RotateMatrix();
      int[][] intArray0 = new int[8][0];
      int[] intArray1 = new int[3];
      intArray0[0] = intArray1;
      // Undeclared exception!
      try { 
        rotateMatrix0.rotate(intArray0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 0, Size: 0
         //
         verifyException("java.util.ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      RotateMatrix rotateMatrix0 = new RotateMatrix();
      int[][] intArray0 = new int[1][8];
      rotateMatrix0.rotate(intArray0);
      assertEquals(1, intArray0.length);
  }
}
