/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 04 07:32:41 GMT 2020
 */

package string;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import string.IsAnagram;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class IsAnagram_ESTest extends IsAnagram_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      IsAnagram isAnagram0 = new IsAnagram();
      assertNotNull(isAnagram0);
      
      boolean boolean0 = isAnagram0.isAnagram("aQvbGMB|P%v86-p%", "string.IsAnagram");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      IsAnagram isAnagram0 = new IsAnagram();
      assertNotNull(isAnagram0);
      
      boolean boolean0 = isAnagram0.isAnagram("BBU:Ir6n+", "BBU:Ir6n+");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      IsAnagram isAnagram0 = new IsAnagram();
      assertNotNull(isAnagram0);
      
      boolean boolean0 = isAnagram0.isAnagram("r8PHYkZ", "");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      IsAnagram isAnagram0 = new IsAnagram();
      assertNotNull(isAnagram0);
      
      // Undeclared exception!
      try { 
        isAnagram0.isAnagram((String) null, "K?K;ImrLNE6h_\"");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("string.IsAnagram", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      IsAnagram isAnagram0 = new IsAnagram();
      assertNotNull(isAnagram0);
      
      boolean boolean0 = isAnagram0.isAnagram("qs$;|V0gjU' vI4&", "string.IsAnagram");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      IsAnagram isAnagram0 = new IsAnagram();
      assertNotNull(isAnagram0);
      
      boolean boolean0 = isAnagram0.isAnagram("af\"T~xq&Z G5M", "qs$;|V0gjU' vI4&");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      IsAnagram isAnagram0 = new IsAnagram();
      boolean boolean0 = isAnagram0.isAnagram("string.IsAnagram", "qs$;|V0gjU' vI4&");
      assertFalse(boolean0);
  }
}
