/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 04 07:35:37 GMT 2020
 */

package string;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import string.LongestCommonPrefix;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class LongestCommonPrefix_ESTest extends LongestCommonPrefix_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LongestCommonPrefix longestCommonPrefix0 = new LongestCommonPrefix();
      String[] stringArray0 = new String[7];
      stringArray0[0] = "U`s@NIS?%{[m^{-0&";
      stringArray0[1] = "@7%/Gs<y3";
      stringArray0[2] = "wB,44";
      // Undeclared exception!
      try { 
        longestCommonPrefix0.longestCommonPrefix(stringArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("string.LongestCommonPrefix", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      String[] stringArray0 = new String[7];
      stringArray0[0] = "string.LongestCommonPrefix";
      stringArray0[1] = "string.LongestCommonPrefix";
      stringArray0[2] = "string.LongestCommonPrefix";
      stringArray0[3] = "string.LongestCommonPrefix";
      stringArray0[4] = "string.LongestCommonPrefix";
      stringArray0[5] = "string.LongestCommonPrefix";
      stringArray0[6] = "string.LongestCommonPrefix";
      LongestCommonPrefix longestCommonPrefix0 = new LongestCommonPrefix();
      String string0 = longestCommonPrefix0.longestCommonPrefix(stringArray0);
      assertEquals("string.LongestCommonPrefix", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      LongestCommonPrefix longestCommonPrefix0 = new LongestCommonPrefix();
      String[] stringArray0 = new String[0];
      String string0 = longestCommonPrefix0.longestCommonPrefix(stringArray0);
      assertEquals("", string0);
  }
}
