/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 04 07:31:25 GMT 2020
 */

package string;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import string.MyAtoi;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class MyAtoi_ESTest extends MyAtoi_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MyAtoi myAtoi0 = new MyAtoi();
      // Undeclared exception!
      try { 
        myAtoi0.myAtoi((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("string.MyAtoi", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      MyAtoi myAtoi0 = new MyAtoi();
      int int0 = myAtoi0.myAtoi("-861");
      assertEquals((-861), int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      MyAtoi myAtoi0 = new MyAtoi();
      int int0 = myAtoi0.myAtoi(" ~\"s7wqH]k");
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      MyAtoi myAtoi0 = new MyAtoi();
      int int0 = myAtoi0.myAtoi("-");
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      MyAtoi myAtoi0 = new MyAtoi();
      int int0 = myAtoi0.myAtoi("6-^\"wH ]IkGLtlF");
      assertEquals(6, int0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      MyAtoi myAtoi0 = new MyAtoi();
      int int0 = myAtoi0.myAtoi("+-W");
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      MyAtoi myAtoi0 = new MyAtoi();
      int int0 = myAtoi0.myAtoi("++zx(\"%kd^4G*H");
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      MyAtoi myAtoi0 = new MyAtoi();
      int int0 = myAtoi0.myAtoi("+ o.H72v/or?o5ci");
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      MyAtoi myAtoi0 = new MyAtoi();
      int int0 = myAtoi0.myAtoi("8+?11e+~T\"");
      assertEquals(8, int0);
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      MyAtoi myAtoi0 = new MyAtoi();
      int int0 = myAtoi0.myAtoi("2 )'|,");
      assertEquals(2, int0);
  }
}
