/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 04 07:38:52 GMT 2020
 */

package string;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import string.ReverseInt;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ReverseInt_ESTest extends ReverseInt_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ReverseInt reverseInt0 = new ReverseInt();
      int int0 = reverseInt0.reverse(1);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ReverseInt reverseInt0 = new ReverseInt();
      int int0 = reverseInt0.reverse((-2147483615));
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ReverseInt reverseInt0 = new ReverseInt();
      int int0 = reverseInt0.reverse(2147483629);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ReverseInt reverseInt0 = new ReverseInt();
      int int0 = reverseInt0.reverse(0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ReverseInt reverseInt0 = new ReverseInt();
      int int0 = reverseInt0.reverse((-1));
      assertEquals((-1), int0);
  }
}
