/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 04 07:42:01 GMT 2020
 */

package string;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import string.ReverseString;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ReverseString_ESTest extends ReverseString_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ReverseString reverseString0 = new ReverseString();
      // Undeclared exception!
      try { 
        reverseString0.reverseString((char[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("string.ReverseString", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ReverseString reverseString0 = new ReverseString();
      char[] charArray0 = new char[2];
      reverseString0.reverseString(charArray0);
      assertArrayEquals(new char[] {'\u0000', '\u0000'}, charArray0);
  }
}
